spring.application.name=pgmaven
spring.main.web-application-type=servlet
server.port=8090

spring.datasource.url=jdbc:postgresql://localhost:5432/pgmaven_db
spring.datasource.username=postgres
spring.datasource.password=Gautier44

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true